<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- 🟢 CORRECTION ICI : Ajout de -windows -->
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.2" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.2" />
    <PackageReference Include="System.Management" Version="10.0.2" />
  </ItemGroup>

</Project>